### ISSUE TITLE
Reordenar contenidos

### ISSUE THREAD

**Issue by dapino** [SIB-Colombia/Biodiversidad-en-cifras#10]
Revisar en: https://sib-colombia.github.io/Biodiversidad-en-cifras/

orden definido:
-MUNDO
-RANKING
-CIFRAS COLOMBIA 
-CARDS: cifras por grupo
-MAPA COLOMBIA
-ESPECIES POR REINO

**Comment by dapino** [comment]
https://sib-colombia.github.io/Biodiversidad-en-cifras/

**Comment by javiesgm** [comment]
Ver issue #11
