### ISSUE TITLE
FOOTER

### ISSUE THREAD

**Issue by dapino** [SIB-Colombia/Biodiversidad-en-cifras#11]
Revisar en: https://sib-colombia.github.io/Biodiversidad-en-cifras/

Footer gris como biodiversidad.co con logo del SiB

**Comment by dapino** [comment]
https://sib-colombia.github.io/Biodiversidad-en-cifras/

**Comment by javiesgm** [comment]
Ajustes: 

1. Cambiar color de fondo para la sección de Especies y Registros por departamento. 
#d2d2d2

2. Fondo para ranking Colombia: #22607b

3. Fondo para preguntas sobre Colombia:  #35b5c5

4. Encabezado. Vámonos de una con biodiversidad en cifras como canal. Esto implica incluirlo en biodiversidad.co
![captura-de-pantalla-2018-08-01-a-la s -10 20 35-a -m](https://user-images.githubusercontent.com/14220404/43532123-ff758942-9576-11e8-820b-2420f906daa3.png)

Footer: solo dejemos el logo del SiB Colombia. 

Tak tak!

Insumos, logo, favicon y demás: https://drive.google.com/file/d/1P5bHiygxdk6myoJtChGzLy4c9gbRD1dv/view?usp=sharing

**Comment by javiesgm** [comment]
@dapino, me faltó incluir en las indicaciones el bloque de los canales de participación. Como en los demás canales. 

![captura de pantalla 2018-08-23 a la s 8 52 45 a m](https://user-images.githubusercontent.com/14220404/44529540-f7b42280-a6b1-11e8-8df4-d383abad49da.png)

**Comment by javiesgm** [comment]
@dapino hay que cambiar el logo también. Antes de la salida de la ventana regional. 
Aquí va: 
https://projects.invisionapp.com/d/main#/projects/boards/6295850/186428697

PNG: 
![l-cifras](https://user-images.githubusercontent.com/14220404/48204781-a6264600-e338-11e8-9bb0-b832a21a908b.png)

**Comment by javiesgm** [comment]
en amazon, blanco: https://s3.amazonaws.com/sib-resources/images/logos-canales/svg/logo-cifras-b.svg

oscuro: 
https://s3.amazonaws.com/sib-resources/images/logos-canales/svg/logo-cifras.svg
