### ISSUE TITLE
Ficha metodológica

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/Biodiversidad-en-cifras#14]
En enlace actual a la ficha metodológica dirije a una hoja de google docs, creo que es mejor que dirija a la versión pdf.

**Comment by javiesgm** [comment]
@camiplata se dejó en google docs para que fuera más fácil mantenerlo actualizado. @leobuitrago qué opinas ? ¿será que lo enlazamos al repositorio Humboldt entonces?

**Comment by camiplata** [comment]
Si, lo estamos trabajando en docs. Yo creo que si vale la pena enlazarlo al repositorio.
