### ISSUE TITLE
Ajustar textos card Insectos

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/Biodiversidad-en-cifras#37]
Cambiar el texto  actual ( "Especies estimadas") dentro del circulo, por: "Especies registradas"

![Screen Shot 2019-04-20 at 22 01 43](https://user-images.githubusercontent.com/5700527/56464901-9ff0c700-63b8-11e9-8493-6431fe6a69b0.png)

**Comment by javiesgm** [comment]
@dapino ten en cuenta #39
