### ISSUE TITLE
El footer se queda 'pegado'

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/Biodiversidad-en-cifras#38]
Al llegar al final de la página e interntar regresar, el footer se queda "pegado"
![7YBi7bC95S](https://user-images.githubusercontent.com/5700527/56465135-640c3080-63bd-11e9-9298-ac6c708f1fb9.gif)
'

**Comment by dapino** [comment]
@camiplata  esto es problema por lo que es un iframe dentro de sibcolombia.net, no tengo una solución que funcione adecuadamente para este problemita, así que voy a cerrar el issue.

**Comment by camiplata** [comment]
@dapino no es mejor dejarlo abierto y ponerlo en backlog?
