### ISSUE TITLE
Títulos inconsistentes en tarjetas por grupo biológico

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/Biodiversidad-en-cifras#39]
Es necesario ajustar los títulos y la gráfica en las cifras generales, dentro de las tarjetas por grupos biológicos. Actualmente, al interior de las tarjetas por grupo biológico que cuentan con estimación con base en listas de referencia: peces de agua dulce, mamíferos y aves, la cifra destacada es la de "Especies registradas" en la gráfica circular "general". Es necesario que en estas tarjetas, la leyenda sea "Especies estimadas". 

![Captura de pantalla 2019-04-30 a la(s) 10.42.05 AM.png](https://images.zenhubusercontent.com/56d4a9026caf56c9d38d0cdd/65759177-b39a-4555-8bbe-804576343527)

En las demás tarjetas, es necesario dejar visible el círculo externo en la gráfica "general", ya que este es el que corresponde a las "Especies registradas" y no, el círculo azul claro, que corresponde a las estimadas. La cifra destacada debe ser "especies registradas".

![Captura de pantalla 2019-04-30 a la(s) 11.08.49 AM.png](https://images.zenhubusercontent.com/56d4a9026caf56c9d38d0cdd/9f04f0d2-7c72-4622-9a8f-62a1371ebc66)

**Comment by dapino** [comment]
En General:
"Especies registradas"
Dejar gráfico externo 
Pero en los tres grupos van las las dos bolas
