### ISSUE TITLE
Incluir fecha de corte de los datos con los que se consolidan las cifras

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/Biodiversidad-en-cifras#41]
Hacer visible la fecha de corte de los datos con los que se construyen las cifras. Incluir justo debajo de los botones de la sección "Sobre las cifras" 

![Captura de pantalla 2019-04-30 a la(s) 11.28.54 AM.png](https://images.zenhubusercontent.com/56d4a9026caf56c9d38d0cdd/deaa4dce-8dae-4264-b769-70d80a605881)

**Comment by camiplata** [comment]
Fecha de corte: 2018-12-31
