### ISSUE TITLE
Ajustar gráfica de estimadas en peces de agua dulce

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/Biodiversidad-en-cifras#42]
Actualmente parece como si las especies registradas no correspondieran con la totalidad de las estimadas y no es así. El círculo externo de la gráfica debería estar completo. 
¿Cierto @camiplata?
 
![Captura de pantalla 2019-04-30 a la(s) 11 31 08 AM](https://user-images.githubusercontent.com/14220404/56977811-b1b23700-6b3b-11e9-936e-0080de1d5e9b.png)

**Comment by camiplata** [comment]
La gráfica representa adecuadamente los datos

**Comment by javiesgm** [comment]
CTRL-Z, esto está bien :)
