### ISSUE TITLE
Incluir botón "Sobre la cifra de especies del país" en la sección "Sobre las Cifras"  

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/Biodiversidad-en-cifras#44]
Incluir un botón que lleve a una página informativa que explique la razón por la cual el SiB Colombia dice que hay 51.330 especies en el país. El referente es la  página sobre los conteos de especies que tiene GBIF. 

El texto del botón es "Sobre la cifra de especies del país" 

La página está pendiente e incluiré el link cuando esté lista. 
El borrador de contenidos es este: 
https://docs.google.com/document/d/1YQzKgXeZbVVf1WeQ86qjqMWiBUEWpCksjaph4PW8n2M/edit?usp=sharing

**Comment by dapino** [comment]
@camiplata Este issue que es?

**Comment by camiplata** [comment]
Este es el documento/ salida de blog que estamos construyendo, cuando este listo te lo compartimos para que puedas hacer el cambio sobre Biodiversidad en Cifras
